# Занятие 3

## NumPy

### 0. Небольшой экскурс в модули

#### 0.1. Модуль

**Модуль** - любой файл с программой

In [ ]:
print("Hello World")

#### 0.2. Использование модулей

Существует также несколько способов использования модулей:
1. Стандартное мпортирование

In [ ]:
#### 1
import math

print(math.pi)

2. Импортирование с заданием имени при обращении к модулю

In [ ]:
import math as m

print(m.pi)

3. Импортирование конкретных переменных/функций/методов/классов

In [ ]:
from math import pi

print(pi)

#### 0.3. Виды модулей

##### 0.3.1. Модули стандартной библиотеки (random, math, time, ...)

Доступны для использования сразу после установки Python

In [ ]:
import random
import math

print(math.pi * random.randint(0,1))

##### 0.3.2. Загружаемые модули

Загружаются через установщик `pip` (`pip3`):

```bash
pip3 install numpy
```

После чего он доступен к использованию

In [ ]:
import numpy

print(numpy.pi)

##### 0.3.3. Собственный модуль

1. Пишется некоторый код, сохраняется в файл
2. В той же папке _(примечание: модуль можно использовать и из других папок, но это требует отдельного рассказа)_ создается еще один файл
3. Файл импортируется в другой _(примечание: но не вместе)_

Пример представлен в папке `myModuleTest`

### 1. NumPy = математика

#### 1.0. Информация и установка

**NumPy** - это библиотека языка Python, добавляющая поддержку больших многомерных массивов и матриц, вместе с большой библиотекой высокоуровневых (и очень быстрых) математических функций для операций с этими массивами.

Для установки NumPy можно использовать пакетный менеджер `pip`, используя команду:

```bash
pip3 install numpy
```

Или скачать c [официального сайта](https://numpy.org/install/)

#### 1.1. Начало работы

Основным объектом является однородный многомерный массив (элементы массива являются одного типа).
В NumPy он представлен типом `numpy.ndarray` и обладает следующими атрибутами:

* `ndarray.ndim` - число измерений (чаще их называют "оси") массива.

* `ndarray.shape` - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.

* `ndarray.size` - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.

* `ndarray.dtype` - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том числе и составные.

* `ndarray.itemsize` - размер каждого элемента массива в байтах.

* `ndarray.data` - буфер, содержащий фактические элементы массива. Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов.

#### 1.2. Создание массива

1. `numpy.array()` - создает объект типа `ndarray` из списков или кортежей **Python**

In [ ]:
import numpy as np

arr = np.array([1,2,3])

print(f"arr = {arr}")
print(f"тип = {type(arr)}")
print(f"осей массива = {arr.ndim}")
print(f"размер массива = {arr.shape}")
print(f"кол-во элементов = {arr.size}")
print(f"тип элемента массива = {arr.dtype}")
print(f"размер каждого элемента в байтах = {arr.itemsize}")
print(f"элементы массива = {arr.data}")

2. `numpy.zeroes()` - n-мерный массив из нулей (`np.ones()` - из единиц)

In [ ]:
import numpy as np

arr = np.zeros(5, dtype=int)
print(f"Массив из 5 нулей =\n{arr}\n")

arr = np.ones((2, 3))
print(f"2-мерный массив размерности 2 на 3 из единиц =\n{arr}")

3. `numpy.eye()` - единичная матрица (двумерный массив)

In [ ]:
import numpy as np

arr = np.eye(5)

print(f"Единичная матрица размера 5:\n{arr}")

4. `numpy.empty()` - пустой n-мерный массив (содержимое зависит от состояния памяти на момент заполнения)

In [ ]:
import numpy as np

arr = np.empty((3,3))

print(f"Пустая матрица 3 на 3:\n{arr}")

5. `numpy.arrange(start, stop, step)` - генерирует массивб начиная с числа `start`, заканчивая `stop` с шагом `step`. Числа могут быть нецелыми.

In [ ]:
import numpy as np

arr = np.arange(0,1,0.1)

print(f"Массив от 0 до 1 с шагом 0.1:\n{arr}")

6. `numpy.fromfunction()` - применяет некоторую функцию ко всем комбинациям индексов

In [ ]:
import numpy as np

def transform(i, j):
  return (i + 1) * (j + 1)

arr = np.fromfunction(transform, (3,3))

print(f"Матрица 3 на 3 с примененной на нее функцией:\n{arr}")

Существуют и еще методы создания, которые могут быть найдены в [официальной документации](https://numpy.org/doc/stable/user/index.html)

#### 1.3. Особенности распечатки массивов

Если массив слишком большой, то NumPy автоматически скрывает центральную часть массива и выводит только его начало и конец.

In [ ]:
import numpy as np

print(np.arange(1, 1002, 1))

Чтобы настроить печать массивов можно использовать следующую глобальную настройку их печати: `numpy.set_printoptions()`, которая принимает следующие параметры:

* `precision` - количество отображаемых цифр после запятой (по умолчанию 8)

* `threshold` - количество элементов в массиве, вызывающее обрезание элементов (по умолчанию 1000).

* `edgeitems` - количество элементов в начале и в конце каждой размерности массива (по умолчанию 3).

* `linewidth` - количество символов в строке, после которых осуществляется перенос (по умолчанию 75).

* `suppress` - если True, не печатает маленькие значения в scientific notation (по умолчанию False).

* `nanstr` - строковое представление NaN (по умолчанию 'nan').

* `infstr` - строковое представление inf (по умолчанию 'inf').

* `formatter` - позволяет более тонко управлять печатью массивов. Здесь я его рассматривать не буду, можете почитать здесь (на английском).

In [ ]:
import numpy as np

np.set_printoptions(threshold=10000)
print(np.arange(1, 2500, 1))

# arr = np.array([np.inf])
# np.set_printoptions(infstr="ничего")
# print(arr)

#### 1.4. Базовые операции

1. Математические операции - выполняются поэлементно (размеры массивов должны _совпадать_). Создается новый массив, являющийся результатом.

In [ ]:
import numpy as np

arr1 = np.array([10,20,30,40,50])
arr2 = np.array([1,2,3,4,5])

print(f"Сложение = {arr1 + arr2}")
print(f"Вычитание = {arr1 - arr2}")
print(f"Умножение = {arr1 * arr2}")
print(f"Деление = {arr1 / arr2}")
print(f"Взятие остатка = {arr1 % arr2}")
print(f"Возведение в степень = {arr1 ** arr2}")

Также можно производить математические операции между массивом и числом.

In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50])
num = 5

print(f"Сложение = {arr + num}")
print(f"Вычитание = {arr - num}")
print(f"Умножение = {arr * num}")
print(f"Деление = {arr / num}")
print(f"Взятие остатка = {arr % num}")
print(f"Возведение в степень = {arr ** num}")

2. Математические операции, которые предоставляет сам NumPy (полный список доступен по [ссылке](https://numpy.org/doc/stable/reference/routines.math.html))

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(f"sin ко всем элементам = {np.sin(arr)}")
print(f"cos ко всем элементам  = {np.cos(arr)}")

3. Унарные операции (как вычисление суммы или нахождение минимума или максимума) (можно найти также по этой [ссылке](https://numpy.org/doc/stable/reference/routines.math.html))

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(f"сумма элементов = {arr.sum()}")
print(f"перемножение = {arr.prod()}")
print(f"min = {arr.min()}")
print(f"max = {arr.max()}")

Применять некоторые операции также можно и к определенной оси n-мерного массива

In [ ]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(f"min в каждом столбце = {arr.min(axis=0)}")
print(f"min в каждой строке = {arr.min(axis=1)}")

#### 1.5. Срезы

Срезы работают ровно также, как и с обычными списками в языке Python. Запрещены лишь операции удаления (почему?)

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(f"arr[1:1] = {arr[1:1]}")
print(f"arr[2:3] = {arr[2:3]}")
print(f"arr[::-1] = {arr[::-1]}")

arr[1:3] = 23
print(f"arr[1:3] = 8 => {arr}")

del arr[1:1] # ошибка!

Если речь идет о n-мерном массиве, то можно передавать индексы для срезов для каждой оси через запятую (по сути, кортежами)

In [ ]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(f"arr[::-1, ::-1] =\n{arr[::-1, ::-1]}\n")

# Если индексов меньше, чем осей, то предполагается дополнение с помозщью срезов,
# то есть выглядит так: arr[::-1, :]
print(f"arr[::-1] =\n{arr[::-1]}") 

#### 1.6. Индексация

Возможно обращение по индексу несколькими способами

In [ ]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(f"arr[1][2] = {arr[1][2]}")
print(f"arr[1,2] = {arr[1,2]}")
print(f"arr[(1,2)] = {arr[(1,2)]}")

Итерирование соответсвует работе со списками

In [ ]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

for row in arr:
  print(row)

При этом присутсвует возможность перебрать n-мерный массив поэлементно, используя аттрибут `flat`

In [ ]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

for el in arr.flat:
  print(el)

#### 1.7. Измнение формы массива

Массив обладает определнной формой. При этом имеется возможность эту форму изменять. Ниже представлены некоторые способы:

* `ravel()` - делает массив одномерным

In [ ]:
import numpy as np

arr = np.array([[[[[1,2,3],
                [4,5,6],
                [7,8,9]]]]])

print(f"arr.ravel() = {arr.ravel()}")

* `transpoce()` - транспонирование

In [ ]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(f"arr.transpose() =\n{arr.transpose()}")

* `shape` - изменение формы массива, `reshape()` - возвращает новый массив измененной формы

In [23]:
import numpy as np

arr = np.array([[1,2,3,4],
                [5,6,7,8]])

arr.shape = (4,2)
print(f"arr.shape = (4,2) =>\n{arr}\n")

print(f"arr.reshape(2,4) =>\n{arr.reshape(2,4)}")

arr.shape = (4,2) =>
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

arr.reshape(2,4) =>
[[1 2 3 4]
 [5 6 7 8]]


* `resize()` - изменяет форму, при этом может обрезать массив или заполнить нулями, если элементов больше, чем в прошлом

In [25]:
import numpy as np

arr = np.array([[1,2,3,4],
                [5,6,7,8]])

arr.resize(3,4)
print(f"arr.resize() =\n{arr}")

arr.resize() =
[[1 2 3 4]
 [5 6 7 8]
 [0 0 0 0]]


#### 1.8. Объединение массивов

* `np.hstack()` - объединение массивов по первым осям (горизонтально)
* `np.vstack()` - объединение массивов по последним осям (вертикально)

In [26]:
import numpy as np

arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr2 = np.array([[10,20,30],
                 [40,50,60]])

print(f"np.hstack(arr1, arr2) =\n{np.hstack((arr1, arr2))}\n")
print(f"np.vstack(arr1, arr2) =\n{np.vstack((arr1, arr2))}")

np.hstack(arr1, arr2) =
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]

np.vstack(arr1, arr2) =
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


#### 1.9. Разбиение массивов

* `np.hsplit()` - разбиение массива по первым осям (горизонтально)
* `np.vsplit()` - объединение массива по последним осям (вертикально)

In [27]:
import numpy as np

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print("np.hsplit(arr, 2) =")
[print(row) for row in np.hsplit(arr, 2)]

print("\nnp.vsplit(arr, 3) =")
[print(row) for row in np.vsplit(arr, 3)]

np.hsplit(arr, 3) =
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]

np.vsplit(arr, 3) =
[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]


[None, None, None]

#### 1.10. Копия

Если попытаться присвоить созданный массив другой переменной, то мы не получим копию массива. Обе переменные будут ссылаться на одну и ту же область памяти

In [28]:
import numpy as np

a = np.array([1,2,3])

b = a

print(f"a is b = {a is b}")

a is b = True


Поверхностная копия (или представление) - данные одинаковые, но можно менять форму, транспонировать и тд

In [29]:
import numpy as np

a = np.arange(12).reshape(3,4)
print(f"a =\n{a}\n")

b = a.view() # создание представления
print(f"b =\n{b}\n")
print(f"b is a = {b is a}\n\n\n")

print("ИЗМЕНЕНА ФОРМА b НА (6,2)")
b.shape = (6,2)
print(f"a =\n{a}\n")
print(f"b =\n{b}\n")

print("ЗНАЧЕНИЯ ИЗМЕНЯЮТСЯ")
b[:] = 23
print(f"a =\n{a}\n")
print(f"b =\n{b}\n")

a =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

b =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

b is a = False



ИЗМЕНЕНА ФОРМА b НА (6,2)
a =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

b =
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

ЗНАЧЕНИЯ ИЗМЕНЯЮТСЯ
a =
[[23 23 23 23]
 [23 23 23 23]
 [23 23 23 23]]

b =
[[23 23]
 [23 23]
 [23 23]
 [23 23]
 [23 23]
 [23 23]]



Глубокая копия - создание абсолютно независимого массива

In [30]:
import numpy as np

a = np.arange(12).reshape(3,4)
b = a.copy() # cоздание глубокой копии

print(f"b is a = {b is a}")
print(f"a =\n{a}\n")
print(f"b =\n{b}\n")

print("\n\nЗНАЧЕНИЯ ИЗМЕНЯЮТСЯ")
b[:] = 23
print(f"a =\n{a}\n")
print(f"b =\n{b}\n")

b is a = False
a =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

b =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



ЗНАЧЕНИЯ ИЗМЕНЯЮТСЯ
a =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

b =
[[23 23 23 23]
 [23 23 23 23]
 [23 23 23 23]]



### 2. Модуль numpy.linalg

#### 2.1. О модуле

**Модуль numpy.linalg** - модуль, позволяющий делать многие операции из линейной алгебры. Документация: [ссылка](https://numpy.org/doc/stable/reference/routines.linalg.html)

#### 2.2. Некотрые примеры

* `linalg.matrix_power(M, n)` - возводит матрицу в степень n

* `linalg.cholesky(a)` - разложение Холецкого

* `linalg.qr(a[, mode])` - QR разложение.

* `linalg.svd(a[, full_matrices, compute_uv])` - сингулярное разложение.

* `linalg.eig(a)` - собственные значения и собственные векторы.

* `linalg.norm(x[, ord, axis])` - норма вектора или оператора.

* `linalg.cond(x[, p])` - число обусловленности.

* `linalg.det(a)` - определитель.

* `linalg.slogdet(a)` - знак и логарифм определителя (для избежания переполнения, если сам определитель очень маленький).

* `linalg.solve(a, b)` - решает систему линейных уравнений Ax = b.

* `linalg.tensorsolve(a, b[, axes])` - решает тензорную систему линейных уравнений Ax = b.

* `linalg.lstsq(a, b[, rcond])` - метод наименьших квадратов.

* `linalg.inv(a)` - обратная матрица.


In [ ]:
import numpy as np
import numpy.linalg as linalg

arr = np.eye(10_000)

print(f"linalg.det(arr) = {linalg.det(arr)}")